# Generated by Django 4.0.6 on 2022-09-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='auther',
            field=models.CharField(max_length=50),
        ),
    ]
